#pragma once

namespace Const
{
	const int SECTION_SIDE = 32, SECTION_HEIGHT = 32;
	const int INIT_CHUNK_NB_SECTIONS = 4;
	const int CHUNK_SIDE = SECTION_SIDE, INIT_CHUNK_HEIGHT = INIT_CHUNK_NB_SECTIONS * SECTION_HEIGHT;

	const int SEA_LEVEL = 64;
}